In [4]:
from numpy import *
class NeuralNetwork(object):
    def __init__(self):
        # seed the genarator
        random.seed(1)
        self.synaptic_weights = 2 * random.random((3,1)) - 1

    def __sigmoid(self, x):
        # the sigmoid function where we pass the weighted sums of the input through this function
        return 1 /(1 + exp(-x))
    
    def predict(self, inputs):
        #Taking the dot product between the input and weight vectors
        return self.__sigmoid(dot(inputs, self.synaptic_weights))

    def __sigmoid_derivative(self, x):
        #derivative of the sigmoid function
        return x * (x - 1)
    def train(self, trainingSetInputs, trainingSetOutputs, numberOfIterations):
        for iteration in range(numberOfIterations):
            output = self.predict(trainingSetInputs)
            error = trainingSetOutputs - output
            #Adjust the next set of weights (back propagation) 
            adjustment = dot(trainingSetInputs.T, error * self.__sigmoid_derivative(output))
            self.synaptic_weights += adjustment
   

if __name__ == '__main__':
    # make one network
    neuralNetwork = NeuralNetwork()
    print('random starting synaptic weights')
    print(neuralNetwork.synaptic_weights)
    print("Initial Error rate")
    print(neuralNetwork.predict(array([1,0,1])))

    # training data
    trainingSetInputs = array([[0,0,1], [1,1,1], [1,0,1], [0,1,1]])
    print("SetInput:")
    print(trainingSetInputs)
    trainingSetOutputs = array([[0,1,1,0]]).T
    print("SetOutput:")
    print(trainingSetOutputs)

    #train the network 1000 times
    neuralNetwork.train(trainingSetInputs, trainingSetOutputs, 1000)

    print('new weights after back propagation')
    print(neuralNetwork.synaptic_weights)

    # test the network
    print("Final Error rate")
    print(neuralNetwork.predict(array([1,0,1])))

random starting synaptic weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Initial Error rate
[0.23762817]
SetInput:
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
SetOutput:
[[0]
 [1]
 [1]
 [0]]
new weights after back propagation
[[-13.2822176 ]
 [  0.43386739]
 [  6.2179114 ]]
Final Error rate
[0.00085436]
